# Generated by Django 6.0.5 on 2026-05-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostmodel',
            old_name='dateline',
            new_name='deadline',
        ),
    ]
